name: DevSecOps Pipeline

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Instalar dependências
        run: composer install

      - name: Instalar Trivy
        run: |
          sudo apt-get update
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Executar scan
        run: |
          trivy fs . --format json -o reports/report.json

      - name: Upload do relatório
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: reports/report.json
